FROM rust:1-slim-bookworm AS builder
RUN cargo install sqlx-cli --version 0.8.6 --no-default-features --features postgres

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/sqlx /usr/local/bin/sqlx
ENTRYPOINT ["sqlx"]
