services:
  realtime-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: realtime-service
    container_name: hermes-realtime-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8092:8092"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
