services:
  guild-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: guild-service
    container_name: hermes-guild-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8086:8086"
      - "50056:50056"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
