services:
  user-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-service
    container_name: hermes-user-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8082:8082"
      - "50052:50052"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
