services:
  channel-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: channel-service
    container_name: hermes-channel-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8083:8083"
      - "50053:50053"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
