services:
  messaging-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: messaging-service
    container_name: hermes-messaging-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8084:8084"
      - "50054:50054"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
