services:
  auth-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service
    container_name: hermes-auth-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
