services:
  chat-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: chat-service
    container_name: hermes-chat-service
    restart: unless-stopped
    env_file: ../../.env
    environment:
      APP_CONFIG_ENV: docker
    ports:
      - "8094:8094"
      - "50064:50064"
    networks:
      - hermes-network

networks:
  hermes-network:
    external: true
