name: Rust Quick Checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  config:
    name: Config Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check config sync
        run: make config-check

  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Check workspace
        run: cargo check --workspace --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Linting
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace
